characters = [
    "Storm",
    "Magik",
    "Wolverine",
    "Danger",
    "Spider-Man",
    "Ms. Marvel",
    "Star-Lord",
    "Peni Parker",
    "Captain America",
    "Iron Man",
    "Hulk",
    "Black Panther",
    "Doctor Doom",
    "Magneto",
    "Green Goblin",
    "Carnage",
    "Ghost Rider",
    "Blade",
    "Deadpool",
    "Loki",
]
